### ISSUE TITLE
Output description

### ISSUE THREAD

**Issue by SSchott** [aqlaboratory/rgn#13]
Finally got it working, after fighting with my CUDA libraries. So I get output, but I would be grateful if you would be a bit more descriptive of the contents in tertiary and recurren_states. Do you have any script to get a PDB-like file to quickly visualize the backbones? 

Additionally, maybe writing explicitly in the README that the GPU definition and memory allocation for protling.py are needed, and that user shouldn't be surprised to get CUDA errors otherwise.

Thanks for sharing the code of such a cool idea!

**Comment by maverick0004** [comment]
.tertiary files contains the 3D coordinates for C alpha , N and C'. 
I am not clear with what are the contents of .recurren_states file. 
Also i want to see dRMSD for validation set, maybe its in RGN12/runs/CASP12/ProteinNet12Thinning90/11/error.log file, i am not sure about that.
Also is there any way to use the coordinates in .tertiary file to visualize the protein ? 
@alquraishi It would be really insightful if you could help with these confusions. Thanks !

**Comment by SSchott** [comment]
@maverick0004 I had that impression from the paper, but unless they are not in order or are in units different than Angstroms, it might be that my test case just went bonkers, as it seems like I have coordinates separated by huge distances (or maybe I am reading this wrong....).

**Comment by stacksideflow** [comment]
The `.tertiary` coordinates are 3x3 matrix mapped to each residue, as described in ProteinNet paper/github repo.

**Comment by alquraishi** [comment]
Sorry for being MIA--just been busy! @SSchott the units are in fact picometers, so that may be why you were thrown off. @maverick0004 the recurrent states files contain just that, the latent state of the RGN. Specifically, it's the concatenation of the forward and backward directions (the last state of each sequence). There are 800 dimensions in each direction hence the 1600 numbers.

The validation dRMSD is in error.log, that's correct. And visualizing the coordinates should be pretty straightforward, as it's literally just a sequence of triplets (x,y,z). I'm pretty sure I have a script in python which I'll try to dig up, but it should be easy to visualize.

**Comment by maverick0004** [comment]
@alquraishi thank you for your prompt reply, it really helps 👍

**Comment by maverick0004** [comment]
@alquraishi .recurren_state file contains 3200 numbers but you said there should be 1600 numbers. Am I missing something ?

**Comment by alquraishi** [comment]
Whoops you're right, I forgot a factor of 2x. Two layers x two directions, where each layer/direction is comprised of 800 units, and so you end up with 3,200 units altogether.

**Comment by SSchott** [comment]
@alquraishi Thanks for the clarifications, it helps.

**Comment by TheKursta** [comment]
Thank you for clarification. Can it be specified further which slices of 3200 units correspond to layer 1 forward, layer 2 reverse, etc.?
